name: fire_alarm_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  uuid: ^3.0.4
  loading_animations: ^2.2.0
  animations: ^2.0.0
  charcode: ^1.2.0
  gradient_widgets: ^0.6.0
  outline_gradient_button: ^2.0.0+1

  # package to draw chart
  syncfusion_flutter_gauges: ^19.1.59
  syncfusion_flutter_charts: ^19.1.59
  linear_gradient: ^0.1.12
  intl: ^0.17.0

  provider: ^5.0.0
  animated_bottom_navigation_bar: ^0.3.2
  after_layout: ^1.1.0
  shared_preferences: ^2.0.5
  sleek_circular_slider : ^2.0.0 #https://pub.dev/packages/sleek_circular_slider
  mqtt_client: ^9.2.0 #https://pub.dev/packages/mqtt_client

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: textTheme
      fonts:
        - asset: assets/fonts/TTHoves-Medium.ttf
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/3d/

